---
title: 'Performance Measure: PI'
author: "Author: Sven Kohler"
date: "23.5.2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r preparation, echo=FALSE, warning=FALSE, message=FALSE}
# source libraries
source("requirements.R")

# load functions file
source("functions_PI.R")
```

```{r data loading, echo=FALSE}
# load data, extract IDs, select relevant columns, fill NA (takes +/- 2 min)
source("load_process_data.R")
```

Implement performance measure

convex combination of average excess return and variance (annualized)

$$
\Pi_p = \lambda*(R_p-R_f)-(1-\lambda)*\sigma_p^2
$$
```{r global variables, echo=FALSE}
#define global variables which are used for performance measure calculations
days_ret <-  252 # trading days, only weekdays in dates (check: unique(weekdays(WikiDaily_selected$date)))
days_vola <- 252 # average number of trading days in a year
min_days <- 1000 # minimum investment period in days
IDs <- max(c(WikiDaily_selected$wiki_nr)) # defines loop to be executed
factor_data_name <- "developed" # define the factor data to be used
verbose <- FALSE
loop <- FALSE # flag if you want to run the whole code or rely on previous results

```

```{r factor data, echo =FALSE}
# get the right factor data (in this calculation not important, only fetches rf)
factor_data <- get_factor_data(factor_data_name)
```

Cross sectional standard deviation of average geometric returns and SDs

$$
avg\_ret_i = \left[ 1+ \left[ \prod_{t=1}^{T_i} (1+(return_t-rf_t)) \right] ^ {\frac{1}{|T|}} \right]^{252}-1 \\ \\
$$
$$
SD\_ret_i = \sqrt{Var(ret_i)*252} \\ \\
$$
$$
CS\_SD_{ret}=\sqrt{\frac{1}{N}\sum_{i=1}^N(avg\_ret_i-mean\_avg\_ret)^2} \\ \\
$$
$$
CS\_SD_{SD}=\sqrt{\frac{1}{N}\sum_{i=1}^N(SD\_ret_i-mean\_SD\_ret)^2}
$$
Calculation of lambda

$$
\lambda=\frac{CS\_SD_{ret}}{CS\_SD_{ret}+CS\_SD_{SD}}
$$

```{r main loop, echo =FALSE}
setwd("C:/Users/svenk/OneDrive/Desktop/UZH/Repo/Performance_Measure/data")
# could optimze the loop by calculating the SRs separately since independent of lambda.
if(loop == TRUE){
  # calculate cross sectional SD of average returns/SDs to get appropriate lambda
  # First: calculate average return/SD of returns per ID
  avg_ret <- rep(0,IDs)
  SDs <- rep(0,IDs)
  # initiate progress bar
  print("Start calculating cross sectional data.")
  pb <- txtProgressBar(min = 0, max = IDs, style = 3, width=100)
  # loop
  for(i in 1:IDs){
    WikiDaily_Id <- WikiDaily_selected[WikiDaily_selected$wiki_nr==i,]
    # merge the different dataframes on date
    WikiDaily_merge <- merge_mult(list_of_dfs=list(WikiDaily_Id, factor_data), by=c("date"))
    avg_ret[i] <- ann_ret(prices =(WikiDaily_merge$ret-WikiDaily_merge$RF), days_ret = days_ret, returns = TRUE)
    SDs[i] <- sqrt(var(WikiDaily_merge$ret-WikiDaily_merge$RF)*days_vola)
    # update progress bar
    setTxtProgressBar(pb, i)
  }
  # Second: calculate SD of avg. returns/SD of returns
  SD_avg_ret <- sqrt(var(avg_ret))
  SD_SDs <- sqrt(var(SDs))
  
  print("End calculating cross sectional data.")
  
  # calculate lambda
  lambda_CS <- SD_avg_ret/(SD_avg_ret+SD_SDs)
  saveRDS(lambda_CS, file=paste0("lambda_CS",".RDS"))
  
  for(name in c("CS", 0, 1)){
    if(name == "CS"){
      lam <- lambda_CS
    }else if(name == 0){
      lam <- 0
    }else if(name==1){
      lam <- 1
    }
    
    # initiate 2 empty matrices to collect performance measures

    # collect performance measures per wiki-ID
    PIs <- matrix(nrow = IDs, ncol=3)
    colnames(PIs) <- c("Total", "1st half", "2nd half") # split in halfs to later calculate autocorrelation between them
    
    # collect sharpe ratios per wiki-ID
    SRs <- matrix(nrow = IDs, ncol=3)
    colnames(SRs) <- c("Total", "1st half", "2nd half") # split in halfs to later calculate autocorrelation between them
    
    # initiate loading bar
    print(paste0("Start calculating Performance Measures for lambda: ", name))
    pb <- txtProgressBar(min = 0, max = IDs, style = 3, width=100) # progress bar
    # loop through all available wiki IDs (takes +/- 10min)
    ignored_IDs <- 0
    for(i in 1:IDs){
      # extract rows (from master data file) corresponding to respective wikiID 
      WikiDaily_Id <- WikiDaily_selected[WikiDaily_selected$wiki_nr==i,]
      # merge the different dataframes on date
      WikiDaily_merge <- merge_mult(list_of_dfs=list(WikiDaily_Id, factor_data), by=c("date"))
      # check whether wikiID satisfies minimum investment period
      if(nrow(WikiDaily_merge)<=min_days){
        ignored_IDs <- ignored_IDs+1
        # get feedback if wanted
        if(verbose==TRUE){
          print(sprintf("Trader with ID %i does not satisfy minimum investment period. Share ignored: %.2f%%", i,
                        ignored_IDs*100/IDs)) 
        }
        next()
      }
      # save start and end date
      start_date <- min(WikiDaily_merge$date)
      end_date <- max(WikiDaily_merge$date)
      # calculate PI for whole investment period
      PIs[i,1] <- PI(prices = WikiDaily_merge$ret, rf=WikiDaily_merge$RF, lambda=lam, returns=TRUE)
      # calculate SR for whole investment period
      SRs[i,1] <- sharpe_ratio(ret=WikiDaily_merge$ret, rf=WikiDaily_merge$RF, 
                               time_adj = TRUE, 
                               time_unit = "years",
                               start_date = start_date, 
                               end_date = end_date)
      # NOW: split investment period in half
      WikiDaily_merge_1st <- WikiDaily_merge[1:round(nrow(WikiDaily_merge)/2),]
      WikiDaily_merge_2nd <- WikiDaily_merge[(round(nrow(WikiDaily_merge)/2)+1):nrow(WikiDaily_merge),]
      # calculate PI for separate halfs
      PIs[i,2] <- PI(prices = WikiDaily_merge_1st$ret, rf=WikiDaily_merge_1st$RF, lambda=lam, returns=TRUE)
      PIs[i,3] <- PI(prices = WikiDaily_merge_2nd$ret, rf=WikiDaily_merge_2nd$RF, lambda=lam, returns=TRUE)
      # calculate SR for separate halfs
      SRs[i,2] <- sharpe_ratio(ret=WikiDaily_merge_1st$ret, rf=WikiDaily_merge_1st$RF, 
                               time_adj = TRUE, 
                               time_unit = "years",
                               start_date = min(WikiDaily_merge_1st$date), 
                               end_date = max(WikiDaily_merge_1st$date))
      SRs[i,3] <- sharpe_ratio(ret=WikiDaily_merge_2nd$ret, rf=WikiDaily_merge_2nd$RF, 
                               time_adj = TRUE, 
                               time_unit = "years",
                               start_date = min(WikiDaily_merge_2nd$date), 
                               end_date = max(WikiDaily_merge_2nd$date))
      # update progress bar
      setTxtProgressBar(pb, i)
    }
    print(paste0("End calculating Performance Measures for lambda: ", name))
    print(paste0("Total: ", IDs, ", Ignored: ", ignored_IDs, ". Fraction ignored: ", round(ignored_IDs*100/IDs, 2),
                 "%."))
    # --> results from last run: [1] "Total: 7340, Ignored: 4233. Fraction ignored: 57.67%." 
    
    # save the RDS file to save time
    saveRDS(PIs, file=paste0("Customized_Performance_Measures_", name,".RDS"))
    saveRDS(SRs, file=paste0("Sharpe_Ratios.RDS"))
  }
}
```

```{r, echo=FALSE}
setwd("C:/Users/svenk/OneDrive/Desktop/UZH/Repo/Performance_Measure/data")
lambda_CS <- readRDS("lambda_CS.RDS")
PIs_CS <- readRDS("Customized_Performance_Measures_CS.RDS")
PIs_0 <- readRDS("Customized_Performance_Measures_0.RDS")
PIs_1 <- readRDS("Customized_Performance_Measures_1.RDS")
SRs <- readRDS("Sharpe_Ratios.RDS")

```

```{r calculate and plot correlations for lambda CS, echo =FALSE, fig.height=15, fig.width=10}
#####################
# calculate various correlation
#####################

# drop NA
clean_PIs <- na.omit(PIs_CS)
clean_SRs <- na.omit(SRs)

# autocorrelation of PI (1st/2nd half)
autoC_PI <- cor(clean_PIs[,2], clean_PIs[,3])
# autocorrelation of SR (1st/2nd half)
autoC_SR <- cor(clean_SRs[,2], clean_SRs[,3])

# correlation between PI and SR
corr_PI_SR <- cor(clean_PIs[,1], clean_SRs[,1])

par(mfrow=c(3,1), oma=c(1.5,2,1,1))
# plot scatter diagram
plot(x = clean_PIs[,1], y=clean_SRs[,1], 
     xlab = "PIs",
     ylab = "SRs",
     main = paste0("Correlation of PI and SR: ", round(corr_PI_SR,3)),
     col=rgb(0,0,0, alpha=0.3))


# plot 1st vs 2nd half
# PIs
plot(x = clean_PIs[,2], y=clean_PIs[,3], 
     xlab = "PI 1st half",
     ylab = "PI 2nd half",
     main = paste0("Autocorrelation of PI: ", round(autoC_PI,3)),
     col=rgb(0,0,0, alpha=0.3))

# SRs
plot(x = clean_SRs[,2], y=clean_SRs[,3], 
     xlab = "SR 1st half",
     ylab = "SR 2nd half",
     main = paste0("Autocorrelation of Sharpe Ratios: ", round(autoC_SR,3)),
     col=rgb(0,0,0, alpha=0.3))

mtext("Correlations for lambda: CS", outer=TRUE,  cex=1, line=-0.5)

# L-shape in plot is artefact from thresholding the SR at zero when negative.
```

```{r calculate and plot correlations for lambda 0, echo =FALSE, fig.height=15, fig.width=10}
#####################
# calculate various correlation
#####################

# drop NA
clean_PIs <- na.omit(PIs_0)
clean_SRs <- na.omit(SRs)

# autocorrelation of PI (1st/2nd half)
autoC_PI <- cor(clean_PIs[,2], clean_PIs[,3])
# autocorrelation of SR (1st/2nd half)
autoC_SR <- cor(clean_SRs[,2], clean_SRs[,3])

# correlation between PI and SR
corr_PI_SR <- cor(clean_PIs[,1], clean_SRs[,1])

par(mfrow=c(3,1), oma=c(1.5,2,1,1))
# plot scatter diagram
plot(x = clean_PIs[,1], y=clean_SRs[,1], 
     xlab = "PIs",
     ylab = "SRs",
     main = paste0("Correlation of PI and SR: ", round(corr_PI_SR,3)),
     col=rgb(0,0,0, alpha=0.3))


# plot 1st vs 2nd half
# PIs
plot(x = clean_PIs[,2], y=clean_PIs[,3], 
     xlab = "PI 1st half",
     ylab = "PI 2nd half",
     main = paste0("Autocorrelation of PI: ", round(autoC_PI,3)),
     col=rgb(0,0,0, alpha=0.3))

# SRs
plot(x = clean_SRs[,2], y=clean_SRs[,3], 
     xlab = "SR 1st half",
     ylab = "SR 2nd half",
     main = paste0("Autocorrelation of Sharpe Ratios: ", round(autoC_SR,3)),
     col=rgb(0,0,0, alpha=0.3))

mtext("Correlations for lambda: 0", outer=TRUE,  cex=1, line=-0.5)

# L-shape in plot is artefact from thresholding the SR at zero when negative.
```

```{r calculate and plot correlations for lambda 1, echo =FALSE, fig.height=15, fig.width=10}
#####################
# calculate various correlation
#####################

# drop NA
clean_PIs <- na.omit(PIs_1)
clean_SRs <- na.omit(SRs)

# autocorrelation of PI (1st/2nd half)
autoC_PI <- cor(clean_PIs[,2], clean_PIs[,3])
# autocorrelation of SR (1st/2nd half)
autoC_SR <- cor(clean_SRs[,2], clean_SRs[,3])

# correlation between PI and SR
corr_PI_SR <- cor(clean_PIs[,1], clean_SRs[,1])

par(mfrow=c(3,1), oma=c(1.5,2,1,1))
# plot scatter diagram
plot(x = clean_PIs[,1], y=clean_SRs[,1], 
     xlab = "PIs",
     ylab = "SRs",
     main = paste0("Correlation of PI and SR: ", round(corr_PI_SR,3)),
     col=rgb(0,0,0, alpha=0.3))


# plot 1st vs 2nd half
# PIs
plot(x = clean_PIs[,2], y=clean_PIs[,3], 
     xlab = "PI 1st half",
     ylab = "PI 2nd half",
     main = paste0("Autocorrelation of PI: ", round(autoC_PI,3)),
     col=rgb(0,0,0, alpha=0.3))

# SRs
plot(x = clean_SRs[,2], y=clean_SRs[,3], 
     xlab = "SR 1st half",
     ylab = "SR 2nd half",
     main = paste0("Autocorrelation of Sharpe Ratios: ", round(autoC_SR,3)),
     col=rgb(0,0,0, alpha=0.3))

mtext("Correlations for lambda: 1", outer=TRUE,  cex=1, line=-0.5)

# L-shape in plot is artefact from thresholding the SR at zero when negative.
```






